100-hours-a-week/1-team-1danhebojo-coalarm-fe

src/components/alarm/AlarmAddModal.jsx
- 알람 설정 모달 추가
- 알람 추가 API 연동 필요
- 코인 목록 조회 API 추가 필요
=> feat: 알람 설정 모달 추가 (API 연동 아직)

src/components/mypage/ProfileSection.jsx
마이페이지에서 프로필 이미지 수정 시 새로고침 하여 사이드바에도 프로필 이미지 갱신되게 수정 하였슴다
=> fix: 프로필 이미지 업로드 후 새로고침 추가

src/components/indicators/FearGreedIndex.jsx, src/components/indicators/LongShortRatio.jsx, src/components/indicators/MacdIndicator.jsx, src/components/indicators/RsiIndicator.jsx, src/pages/Dashboard.jsx
대시보드 MACD, RSI, 롱숏 비율 API 연동 및 스타일 수정했슴다
=> feat: 대시보드 MACD, RSI, 롱숏 비율 API 연동 및 스타일 수정

src/components/alarm/AlarmAddModal.jsx
=> feat: 알람 모달 추가

src/components/indicators/KimchiPremium.jsx, src/pages/Dashboard.jsx
=> 김치프리미엄 API 연동 및 UI 수정

src/components/alert/AlarmAddModal.jsx
=> fix: 잘못된 코드 추가

src/components/alert/AlarmAddModal.jsx, src/pages/alert/AlertPage.jsx, src/redux/createAlertModalSlice.js, src/redux/store.js
=> 알람 목록 페이지와 알람 생성 모달 연동

package-lock.json, package.json, src/components/indicators/KimchiPremium.jsx, src/components/transactions/TransactionList.jsx, src/pages/Dashboard.jsx
- framer-motion 라이브러리 추가
- 웹소켓 연결을 통한 실시간 거래 데이터 수신 구현
- 거래 내역 목데이터 제거 및 API 데이터 연동
=> feat: 실시간 거래 내역 구현 및 UI 개선

src/components/alert/AlarmAddModal.jsx, src/pages/alert/AlertPage.jsx
- 활성화 된 버튼 색상 변경
- 알람 모달과 알람 페이지 연결
- 지정가를 이미 선택한 상태에서 선택할 때 값 변경
=> fix: 활성화 된 버튼 색상 변경

src/components/alert/AlarmAddModal.jsx
- 알람 등록 시 409/500 오류를 catch로 가지 않도록 Axios 응답 처리 개선
=> feat: 알람 등록 시 409/500 오류를 catch로 가지 않도록 Axios 응답 처리 개선

src/components/dashboard/CoinSearch.jsx, src/components/transactions/TransactionList.jsx, src/pages/Dashboard.jsx
- 고래 체결 내역 기준 1억에서 1,000만원으로 변경
- Dashboard.jsx에서 기존 검색 로직 제거 후 CoinSearch 컴포넌트를 사용하도록 수정
- UI 개선 :  스크롤바 커스터마이징 및 검색 기록 최대 5개까지 출력
=> 고래 체결 내역 기준 변경 및 검색 기능 추가

src/pages/alert/AlertPage.jsx
=> feat: 알람 추가 시 최신순으로 정렬 추가

src/components/common/Tooltip.jsx, src/components/dashboard/CoinSearch.jsx, src/components/indicators/FearGreedIndex.jsx, src/components/indicators/KimchiPremium.jsx, src/components/indicators/LongShortRatio.jsx, src/components/indicators/MacdIndicator.jsx, src/components/indicators/RsiIndicator.jsx, src/components/transactions/TransactionList.jsx, src/pages/Dashboard.jsx, src/pages/Mypage.jsx
- 툴팁 컴포넌트 적용
- 코인 검색 시 드롭다운으로 표시
- 검색 입력 시 2글자 이상일 경우 자동으로 API 호출
=> 툴팁 컴포넌트 적용 및 코인 검색 기능 개선

src/index.css, tailwind.config.js
=> feat: 폰트 적용 (Pretendard)

src/components/Sidebar.jsx, src/pages/Mypage.jsx
- 사이드바 하단에 있던 '디스코드 바로가기' 버튼 제거
- 마이페이지에서 주석 처리되어 있던 '회원 탈퇴하기' 링크 복원
=> style: 사이드바 디스코드 버튼 제거 및 회원 탈퇴 링크 복구

package-lock.json, package.json, src/App.jsx, src/components/toast/AlertContext.jsx, src/components/toast/Toast.jsx, tailwind.config.js
- SSE 연결 하는 코드 추가
- SSE로 데이터 받아서 토스트로 알람 보여주게 추가
=> feat: SSE 토스트 메세지 추가

src/components/transactions/TransactionList.jsx, src/utils/upbitWebSocket.js
- 개별 웹소켓 연결 방식에서 공유 웹소켓 방식으로 변경
- upbitWebSocket.js 유틸리티 추가하여 중앙화된 웹소켓 관리
- 배포 환경 테스트 필요
=> feat: 웹소켓 연결 방식 개선

src/components/dashboard/CoinSearch.jsx
검색 중 "검색 결과가 없습니다" 메시지를 자연스럽게 표시하고, isLoading 상태 및 관련 UI 제거로 UX 개선
=> refactor: 코인 검색 결과 없을 때 메시지 표시 및 로딩 상태 제거

src/components/indicators/FearGreedIndex.jsx, src/pages/Dashboard.jsx
- FearGreedIndex 컴포넌트에 로딩 상태 표시 기능 추가
- Dashboard 컴포넌트의 fearGreedIndex 초기값을 55.0에서 null로 변경
- API 응답 대기 중 로딩 애니메이션 표시로 사용자 경험 개선
=> fix: 공포탐욕 지수 초기 로딩 상태 개선

src/api/userApi.jsx, src/components/mypage/NotificationSection.jsx, src/pages/Mypage.jsx
=> fix: 마이페이지 알람 내역 화면 개선

src/api/dashboardApi.jsx, src/components/alert/AlarmAddModal.jsx, src/components/dashboard/CoinSearch.jsx
=> feat : 현재가를 포함한 코인 검색 API 연동

src/components/modals/DiscordWebhookModal.jsx
=> fix: 디스코드 연동 가이드 안내 수정

src/components/Header.jsx
=> fix: 불필요한 햄버거 버튼 삭제

src/components/mypage/ProfileSection.jsx
- 2자~10자 이내로 제한
- 플레이스 홀더 문구도 수정
Close #72 , #73
=> fix: 닉네임 유효성 검사 로직 추가

src/components/indicators/KimchiPremium.jsx
=> fix: 김치 프리미엄 이미지 박스 배치 이슈 해결

src/components/alert/AlarmAddModal.jsx, src/components/alert/ToggleSwitch.jsx
=> fix: 토글 색상 변경

src/pages/alert/AlertPage.jsx, tailwind.config.js
=> fix: 알람 설정 페이지 다중 알람 설정시 UI 깨짐

src/pages/Discord.jsx
=> fix: 디스코드 연동 된 유저는 로그인 후 대시보드로 이동하게 수정

src/components/alert/AlarmAddModal.jsx
- 드롭다운에서 '직접 입력하기' 선택 시만 input 활성화되도록 수정
- 퍼센트 입력 시 음수 허용 및 최대 허용 범위를 -99~99로 제한
- Resolves #88
=> fix: 직접 입력 시 지정가 퍼센트 음수/최대값 제한 및 입력 오류 수정

src/components/alert/AlarmAddModal.jsx
=> refactor: 직접 입력하기 -> 직접 입력

src/api/axios.jsx, src/components/transactions/TransactionList.jsx
=> 429 에러 처리 로직 추가 및 로그 제거

src/pages/Login.jsx
- 로그인 페이지에서 DevTools 열 시 글자 밀림 현상 수정
resolved #96
=> fix: 로그인 페이지에서 DevTools 열 시 글자 밀림 현상 수정

src/api/userApi.jsx, src/components/mypage/DiscordIntegrationSection.jsx
백엔드에 새롭게 추가된 디스코드 웹훅 연동 해제 API와 연동
=> fix: 디스코드 웹훅 연동 해제 이슈 해결

src/components/indicators/MacdIndicator.jsx, src/components/toast/AlertContext.jsx
=> fix: macd 단위 수정

src/components/toast/AlertContext.jsx
- 토스트 메세지에 나오는 소리 알람을 끌 수 있게 하였음
=> feat: 토스트 메시지 소리 설정

src/components/mypage/NotificationSection.jsx
- 백엔드 offset 처리 방식에 맞춰 페이지 번호 기반 요청으로 수정
- 페이지네이션에서 최대 표시 페이지 수를 3 -> 5로 변경
- Close #107
=> fix: 알람 내역 페이지네이션 오류 수정

src/App.jsx, src/components/Sidebar.jsx, src/utils/cookieUtils.js
기본 경로를 로그인 페이지에서 대시보드 페이지로 변경했습니다.
로그인 상태에 따라 조건부 렌더링하여 로그인 시 로그아웃 버튼 표시, 비로그인 시 로그인 버튼 뜨게 수정했습니다.
비로그인 상태에서 알람 목록 접근 시 모달창 뜨게 수정 필요합니다.
=> feat: 기본 경로 수정 및 로그인 상태에 따라 조건부 렌더링

src/components/Sidebar.jsx, src/components/modals/LoginRequiredModal.jsx, src/components/mypage/WithdrawalConfirmationModal.jsx, src/components/toast/AlertContext.jsx, src/pages/alert/AlertPage.jsx
- 로그인 요청 모달 추가 
- 토스트 메세지 디테일 추가 및 수정
=> 프론트 디테일 수정

src/pages/alert/AlertPage.jsx
- 알람 설정 페이지에서 사용자가 로그인 하지 않을시 무한 요청을 보내는 버그를 발견
- 지연 로딩과 최대 재시도 횟수를 제한하였음
=> fix: 알림 설정 페이지 무한 요청 수정

src/api/dashboardApi.jsx, src/components/indicators/KimchiPremium.jsx
- KimchiPremium 컴포넌트에 무한 스크롤 기능 구현
- 한 번에 불러오는 결과 수를 5개에서 20개로 증가
=> feat: 김치 프리미엄 컴포넌트에 무한 스크롤 추가

src/components/Header.jsx
=> feat: Clarity 추가

src/App.jsx, src/components/Clarity.js, src/components/Header.jsx
=> feat: Clarity 분리

src/App.jsx, src/components/Clarity.js, src/components/Sidebar.jsx, src/components/alert/AlarmAddModal.jsx, src/components/modals/DiscordWebhookModal.jsx, src/components/mypage/AlarmDetailModal.jsx, src/components/mypage/DiscordIntegrationSection.jsx, src/components/mypage/NotificationSection.jsx, src/components/mypage/ProfileAvatar.jsx, src/components/mypage/ProfileSection.jsx, src/components/mypage/WithdrawalConfirmationModal.jsx, src/components/toast/AlertContext.jsx, src/components/transactions/TransactionList.jsx, src/pages/Dashboard.jsx, src/pages/Discord.jsx, src/pages/Mypage.jsx, src/pages/alert/AlertPage.jsx, src/utils/upbitWebSocket.js
- "알림" -> "알람"으로 키워드 변경
- 마이페이지의 "알람 내역" -> "알람 히스토리" 로 키워드 변경 
-  Close #125 
- 디스코드 상단 마진 추가
- Close #126
- 불필요한 console.log 제거
- Close #124
=> fix: 이슈 처리

src/components/alert/AlarmAddModal.jsx
=> refactor: targetPrice 알람 갯수 제한 추가

src/components/alert/AlarmAddModal.jsx, src/components/dashboard/CoinSearch.jsx
=> 코인 검색 debounce 수정

src/pages/alert/AlertPage.jsx
=> refactor: 정렬 버튼 커스텀

src/App.jsx
=> fix: 로그인 화면 사이드바 메뉴 노출 수정

src/components/Sidebar.jsx
=> refactor: 가격 예측 메뉴 노출 수정

src/components/mypage/AlarmDetailModal.jsx
- 'bg-[#B7BFFF]' : 'bg-[#0A1672]' -> 'bg-[#4ADE80]' : 'bg-[#c4c4c4]'
=> fix: 알람 이력 모달의 알람 유형 색상 수정
